#!/usr/bin/env bash
#
# Copyright (c) Mathis Engelbart. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
#
# Copies the SCReAM sources needed by this wrapper out of the Git submodule
# into the package directory, where cgo compiles them.
#
# Usage: scripts/vendor-scream.sh [destination]
#
# The destination defaults to the repository root. Run it via `make vendor`
# after updating the submodule, and `make check-vendor` to verify the vendored
# copy is in sync.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUBMODULE="${REPO_ROOT}/scream"
SRC="${SUBMODULE}/code"
DST="${1:-${REPO_ROOT}}"

# The upstream sources the wrapper compiles. The wrapper's own files all carry a
# C suffix (ScreamTxC, ScreamRxC, RtpQueueC) so that they never collide with
# these.
FILES=(
  RtpQueue.h
  ScreamRx.h
  ScreamTx.h
  ScreamRx.cpp
  ScreamTx.cpp
  ScreamV2Tx.cpp
  ScreamV2TxStream.cpp
)

if [ ! -f "${SRC}/ScreamTx.h" ]; then
  echo "error: ${SRC} is empty, run: git submodule update --init" >&2
  exit 1
fi

COMMIT="$(git -C "${SUBMODULE}" rev-parse HEAD)"
URL="$(git -C "${REPO_ROOT}" config --file .gitmodules submodule.scream.url)"

mkdir -p "${DST}"

# Keep the license this repository ships for the vendored code identical to
# upstream's own.
cp "${SUBMODULE}/LICENSE" "${DST}/LICENSE_SCREAM"

for f in "${FILES[@]}"; do
  if [ ! -f "${SRC}/${f}" ]; then
    echo "error: ${SRC}/${f} does not exist, upstream layout changed" >&2
    exit 1
  fi

  {
    # The license itself is not repeated per file, upstream ships it as a top
    # level file and LICENSE_SCREAM retains it. This header is here so that a
    # reader can tell these files apart from the wrapper's own.
    echo "// Vendored from ${URL}"
    echo "// commit ${COMMIT}, code/${f}"
    echo "//"
    echo "// Copyright (c) 2015, Ericsson AB. All rights reserved."
    echo "// Licensed under BSD-2-Clause, see LICENSE_SCREAM."
    echo "//"
    echo "// Generated by scripts/vendor-scream.sh, do not edit."
    cat "${SRC}/${f}"
  } > "${DST}/${f}"
done

echo "vendored ${#FILES[@]} files from ${COMMIT}"
